# Generated by Django 4.2.5 on 2023-09-30 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DefinitionExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("english_example", models.CharField(max_length=255)),
                ("oshindonga_example", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnglishWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                (
                    "word",
                    models.CharField(
                        error_messages={
                            "unique": "The English word you entered already exists in the dictionary."
                        },
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "word_case",
                    models.CharField(
                        choices=[
                            ("Abbreviation", "Abbreviation"),
                            ("Proper Noun", "Proper Noun"),
                            ("Normal", "Normal"),
                        ],
                        default="Normal",
                        help_text="Indicate whether the word you are entering is a normal word, abbretiation or proper noun.",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalDefinitionExample",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                ("english_example", models.CharField(max_length=255)),
                ("oshindonga_example", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical definition example",
                "verbose_name_plural": "historical definition examples",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEnglishWord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "word",
                    models.CharField(
                        db_index=True,
                        error_messages={
                            "unique": "The English word you entered already exists in the dictionary."
                        },
                        max_length=50,
                    ),
                ),
                (
                    "word_case",
                    models.CharField(
                        choices=[
                            ("Abbreviation", "Abbreviation"),
                            ("Proper Noun", "Proper Noun"),
                            ("Normal", "Normal"),
                        ],
                        default="Normal",
                        help_text="Indicate whether the word you are entering is a normal word, abbretiation or proper noun.",
                        max_length=12,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical english word",
                "verbose_name_plural": "historical english words",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOshindongaIdiom",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                ("oshindonga_idiom", models.CharField(max_length=255)),
                ("meaning", models.CharField(blank=True, max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical oshindonga idiom",
                "verbose_name_plural": "historical oshindonga idioms",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOshindongaPhonetic",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                ("oshindonga_phonetics", models.CharField(max_length=50)),
                (
                    "oshindonga_pronunciation",
                    models.TextField(blank=True, max_length=100),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical oshindonga phonetic",
                "verbose_name_plural": "historical oshindonga phonetics",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPartOfSpeech",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                ("code", models.CharField(max_length=4)),
                ("english_name", models.CharField(max_length=50)),
                ("oshindonga_name", models.CharField(max_length=50)),
                ("example", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical part of speech",
                "verbose_name_plural": "historical part of speechs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWordPair",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                ("oshindonga_word", models.CharField(max_length=50)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical word pair",
                "verbose_name_plural": "historical word pairs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWordPairDefinition",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                ("english_definition", models.CharField(blank=True, max_length=255)),
                ("oshindonga_definition", models.CharField(blank=True, max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical word pair definition",
                "verbose_name_plural": "historical word pair definitions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OshindongaIdiom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("oshindonga_idiom", models.CharField(max_length=255)),
                ("meaning", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OshindongaPhonetic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("oshindonga_phonetics", models.CharField(max_length=50)),
                (
                    "oshindonga_pronunciation",
                    models.FileField(blank=True, upload_to="oshindonga_pronunciations"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartOfSpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=4)),
                ("english_name", models.CharField(max_length=50)),
                ("oshindonga_name", models.CharField(max_length=50)),
                ("example", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnfoundWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=50)),
                ("time_searched", models.DateTimeField(auto_now_add=True)),
                ("search_count", models.IntegerField(default=1)),
                ("added_to_dict", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="WordPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("oshindonga_word", models.CharField(max_length=50)),
                (
                    "english_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.english-word",
                    ),
                ),
                (
                    "part_of_speech",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dictionary.partofspeech",
                    ),
                ),
                (
                    "root",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="dictionary.wordpair",
                    ),
                ),
                ("synonyms", models.ManyToManyField(to="dictionary.wordpair")),
            ],
        ),
        migrations.CreateModel(
            name="WordPairDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("english_definition", models.CharField(blank=True, max_length=255)),
                ("oshindonga_definition", models.CharField(blank=True, max_length=255)),
                (
                    "word_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definitions",
                        to="dictionary.wordpair",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="unfoundword",
            constraint=models.UniqueConstraint(
                fields=("word", "language"), name="unique_unfound_word"
            ),
        ),
        migrations.AddField(
            model_name="oshindongaphonetic",
            name="word_pair",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="dictionary.wordpair"
            ),
        ),
        migrations.AddField(
            model_name="oshindongaidiom",
            name="word_pair",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dictionary.wordpair"
            ),
        ),
        migrations.AddField(
            model_name="historicalword-pair-definition",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalword-pair-definition",
            name="word_pair",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.wordpair",
            ),
        ),
        migrations.AddField(
            model_name="historicalwordpair",
            name="english_word",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.english-word",
            ),
        ),
        migrations.AddField(
            model_name="historicalwordpair",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalwordpair",
            name="part_of_speech",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.partofspeech",
            ),
        ),
        migrations.AddField(
            model_name="historicalwordpair",
            name="root",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.wordpair",
            ),
        ),
        migrations.AddField(
            model_name="historicalpartofspeech",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaloshindongaphonetic",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaloshindongaphonetic",
            name="word_pair",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.wordpair",
            ),
        ),
        migrations.AddField(
            model_name="historicaloshindongaidiom",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaloshindongaidiom",
            name="word_pair",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.wordpair",
            ),
        ),
        migrations.AddField(
            model_name="historicalenglish-word",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinition-example",
            name="definition",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.word-pair-definition",
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinition-example",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="definition-example",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary.word-pair-definition",
            ),
        ),
        migrations.AddConstraint(
            model_name="wordpair",
            constraint=models.UniqueConstraint(
                fields=("english_word", "oshindonga_word", "part_of_speech"),
                name="unique_word_pair",
            ),
        ),
    ]
