# Generated by Django 4.2.5 on 2023-10-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpartofspeech",
            name="example",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpartofspeech",
            name="oshindonga_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="partofspeech",
            name="example",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="partofspeech",
            name="oshindonga_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
