# Generated by Django 4.2.5 on 2023-10-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0002_alter_historicalpartofspeech_example_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpartofspeech",
            name="code",
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="historicalpartofspeech",
            name="english_name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="partofspeech",
            name="code",
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name="partofspeech",
            name="english_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
